// Generated by CoffeeScript 1.3.1
(function() {
  var app, env, express, oauth, _ref;

  express = require("express");

  env = require("../config/env");

  oauth = {
    config: env.oauth,
    middleware: require("./middleware/oauth"),
    events: require("./controllers/oauth").events
  };

  app = module.exports = express.createServer();

  app.configure(function() {
    app.set("views", __dirname + "/views");
    app.set("view engine", "jade");
    app.use(express.bodyParser());
    app.use(express.methodOverride());
    app.use(express.cookieParser());
    app.use(express.session({
      secret: env.app.secret
    }));
    app.use(oauth.middleware(app, oauth.events, oauth.config));
    app.use(app.router);
    return app.use(express["static"](__dirname + "/../public"));
  });

  app.configure("development", function() {
    return app.use(express.errorHandler({
      dumpExceptions: true,
      showStack: true
    }));
  });

  app.configure("production", function() {
    return app.use(express.errorHandler());
  });

  app.dynamicHelpers({
    request: function(req, res) {
      return req;
    },
    session: function(req, res) {
      return req.session;
    },
    user: function(req, res) {
      return req.session.user;
    },
    messages: require("express-messages-bootstrap")
  });

  require("../config/routes")(app);

  app.listen((((_ref = process.argv) != null ? _ref.length : void 0) && parseInt(process.argv[2])) || 3001);

  console.log("Listening on port " + (app.address().port) + " in " + app.settings.env + " mode");

}).call(this);
